[2025-08-30T14:15:39.861+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-30T14:15:39.880+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_confirm_query manual__2025-08-30T14:15:36.861845+00:00 [queued]>
[2025-08-30T14:15:39.888+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_confirm_query manual__2025-08-30T14:15:36.861845+00:00 [queued]>
[2025-08-30T14:15:39.888+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-08-30T14:15:39.898+0000] {taskinstance.py:2907} INFO - Executing <Task(SQLExecuteQueryOperator): execute_sql_confirm_query> on 2025-08-30 14:15:36.861845+00:00
[2025-08-30T14:15:39.903+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=596) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-30T14:15:39.904+0000] {standard_task_runner.py:72} INFO - Started process 597 to run task
[2025-08-30T14:15:39.905+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_loader', 'execute_sql_confirm_query', 'manual__2025-08-30T14:15:36.861845+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/postgres_loader.py', '--cfg-path', '/tmp/tmpwj35epi1']
[2025-08-30T14:15:39.907+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask execute_sql_confirm_query
[2025-08-30T14:15:39.953+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_loader.execute_sql_confirm_query manual__2025-08-30T14:15:36.861845+00:00 [running]> on host da5edb323d01
[2025-08-30T14:15:40.025+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_loader' AIRFLOW_CTX_TASK_ID='execute_sql_confirm_query' AIRFLOW_CTX_EXECUTION_DATE='2025-08-30T14:15:36.861845+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-30T14:15:36.861845+00:00'
[2025-08-30T14:15:40.026+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-08-30T14:15:40.037+0000] {sql.py:306} INFO - Executing: 
        INSERT INTO sample_table (key, value)
        VALUES ('sensor', 'confirmed')
    
[2025-08-30T14:15:40.045+0000] {base.py:84} INFO - Retrieving connection 'my_postgres_connection'
[2025-08-30T14:15:40.054+0000] {base.py:84} INFO - Retrieving connection 'my_postgres_connection'
[2025-08-30T14:15:40.058+0000] {sql.py:814} INFO - Running statement: 
        INSERT INTO sample_table (key, value)
        VALUES ('sensor', 'confirmed')
    , parameters: None
[2025-08-30T14:15:40.059+0000] {sql.py:823} INFO - Rows affected: 1
[2025-08-30T14:15:40.070+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-08-30T14:15:40.070+0000] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=postgres_loader, task_id=execute_sql_confirm_query, run_id=manual__2025-08-30T14:15:36.861845+00:00, execution_date=20250830T141536, start_date=20250830T141539, end_date=20250830T141540
[2025-08-30T14:15:39.904+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-30T14:15:39.916+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-30T14:15:39.917+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
